# Generated by Django 5.2.17 on 2026-09-26 12:25

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('account_type', models.CharField(choices=[('CASH', 'Cash'), ('INVESTMENT', 'Investment'), ('FEE_EXPENSE', 'Fee Expense'), ('GAIN_LOSS', 'Gain Loss'), ('LP_CAPITAL', 'Lp Capital'), ('GP_CAPITAL', 'Gp Capital')], max_length=32)),
                ('currency', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='funds.fund')),
                ('owner_lp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='funds.limitedpartner')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('request_hash', models.CharField(blank=True, default='', max_length=64)),
                ('transfer_type', models.CharField(choices=[('CAPITAL_CALL', 'Capital Call'), ('DISTRIBUTION', 'Distribution'), ('FEE', 'Fee'), ('INVESTMENT', 'Investment'), ('REVERSAL', 'Reversal'), ('ADJUSTMENT', 'Adjustment')], max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='funds.period')),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='ledger.transfer')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('currency', models.CharField(max_length=3)),
                ('fx_rate', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('base_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('signed_amount', models.GeneratedField(db_persist=True, expression=models.Case(models.When(direction='DEBIT', then=models.F('amount')), default=django.db.models.expressions.CombinedExpression(models.F('amount'), '*', models.Value(-1)), output_field=models.DecimalField(decimal_places=4, max_digits=20)), output_field=models.DecimalField(decimal_places=4, max_digits=20))),
                ('signed_base_amount', models.GeneratedField(db_persist=True, expression=models.Case(models.When(direction='DEBIT', then=models.F('base_amount')), default=django.db.models.expressions.CombinedExpression(models.F('base_amount'), '*', models.Value(-1)), output_field=models.DecimalField(decimal_places=4, max_digits=20)), output_field=models.DecimalField(decimal_places=4, max_digits=20))),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.account')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.transfer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='account_currency_iso4217'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('account_type', 'LP_CAPITAL'), ('owner_lp__isnull', False)), models.Q(models.Q(('account_type', 'LP_CAPITAL'), _negated=True), ('owner_lp__isnull', True)), _connector='OR'), name='account_owner_lp_iff_lp_capital'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('fund', 'code'), name='account_code_unique_per_fund'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('account_type', 'LP_CAPITAL')), fields=('fund', 'owner_lp', 'currency'), name='account_one_lp_capital_per_lp_currency'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('id', 'currency'), name='account_id_currency_unique'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.UniqueConstraint(fields=('idempotency_key',), name='transfer_idempotency_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.UniqueConstraint(fields=('reverses',), name='transfer_reverses_unique'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), name='transfer_idempotency_key_present'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(condition=models.Q(('reverses__isnull', True), ('transfer_type', 'REVERSAL'), _connector='OR'), name='transfer_only_reversals_reverse'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('transfer_type', 'REVERSAL'), _negated=True), ('reverses__isnull', False), _connector='OR'), name='transfer_reversal_has_target'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['account', 'created_at'], name='entry_account_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='entry_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(('base_amount__gt', 0)), name='entry_base_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='entry_currency_iso4217'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(('direction__in', ['DEBIT', 'CREDIT'])), name='entry_direction_valid'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(('fx_rate__isnull', True), ('fx_rate__gt', 0), _connector='OR'), name='entry_fx_rate_positive'),
        ),
    ]
