# Generated by Django 5.2.17 on 2026-09-26 01:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LimitedPartner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('investor_type', models.CharField(choices=[('PENSION', 'Pension'), ('ENDOWMENT', 'Endowment'), ('SOVEREIGN_WEALTH', 'Sovereign Wealth'), ('FAMILY_OFFICE', 'Family Office'), ('FUND_OF_FUNDS', 'Fund Of Funds'), ('INSURANCE', 'Insurance')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('base_currency', models.CharField(max_length=3)),
                ('vintage_year', models.PositiveSmallIntegerField()),
                ('inception_date', models.DateField()),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('base_currency__regex', '^[A-Z]{3}$')), name='fund_base_currency_iso4217')],
            },
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('as_of_date', models.DateField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('from_currency', 'to_currency', 'as_of_date'), name='fxrate_unique_per_day'), models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='fxrate_positive'), models.CheckConstraint(condition=models.Q(('from_currency', models.F('to_currency')), _negated=True), name='fxrate_distinct_currencies')],
            },
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('committed_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('signed_date', models.DateField()),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commitments', to='funds.fund')),
                ('lp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commitments', to='funds.limitedpartner')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fund', 'lp'), name='commitment_one_per_lp_per_fund'), models.CheckConstraint(condition=models.Q(('committed_amount__gt', 0)), name='commitment_amount_positive')],
            },
        ),
        migrations.CreateModel(
            name='NavSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('as_of_date', models.DateField()),
                ('total_nav', models.DecimalField(decimal_places=4, max_digits=20)),
                ('computed_at', models.DateTimeField()),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nav_snapshots', to='funds.fund')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fund', 'as_of_date'), name='nav_one_per_fund_per_day')],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=6)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='funds.fund')),
            ],
            options={
                'ordering': ['fund', 'start_date'],
                'constraints': [models.UniqueConstraint(fields=('fund', 'start_date'), name='period_unique_start'), models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='period_end_not_before_start'), models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', True), ('status', 'OPEN')), models.Q(('closed_at__isnull', False), ('status', 'CLOSED')), _connector='OR'), name='period_closed_at_matches_status')],
            },
        ),
    ]
