# Generated by Django 5.2.17 on 2026-09-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='closed_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
