# Generated by Django 5.2.17 on 2026-09-27 14:40

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funds', '0001_initial'),
        ('ledger', '0002_integrity_triggers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_number', models.PositiveIntegerField()),
                ('notice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capital_calls', to='funds.fund')),
                ('transfer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='capital_call', to='ledger.transfer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fund', 'call_number'), name='capital_call_number_unique'), models.CheckConstraint(condition=models.Q(('total_amount__gt', 0)), name='capital_call_positive'), models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('notice_date'))), name='capital_call_due_after_notice')],
            },
        ),
    ]
