# Generated by Django 5.2.17 on 2026-09-28 00:33

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
        ('ledger', '0002_integrity_triggers'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distribution_number', models.PositiveIntegerField()),
                ('payment_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('classification', models.CharField(choices=[('RETURN_OF_CAPITAL', 'Return Of Capital'), ('GAIN', 'Gain'), ('INCOME', 'Income')], max_length=32)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='funds.fund')),
                ('transfer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='distribution', to='ledger.transfer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fund', 'distribution_number'), name='distribution_number_unique'), models.CheckConstraint(condition=models.Q(('total_amount__gt', 0)), name='distribution_positive')],
            },
        ),
    ]
