# Generated by Django 5.2.17 on 2026-09-28 21:29

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('prefix', models.CharField(max_length=12)),
                ('key_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('prefix',), name='apikey_prefix_unique'), models.CheckConstraint(condition=models.Q(('key_hash__regex', '^[0-9a-f]{64}$')), name='apikey_hash_is_sha256')],
            },
        ),
        migrations.CreateModel(
            name='FundMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('LP', 'Limited partner: own statement only'), ('VIEWER', 'Viewer: read the whole fund'), ('OPERATOR', 'Operator: also post calls, distributions, reversals'), ('CONTROLLER', 'Controller: also close periods')], max_length=16)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='funds.fund')),
                ('lp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='funds.limitedpartner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'fund'), name='membership_one_per_user_fund'), models.CheckConstraint(condition=models.Q(models.Q(('role', 'LP'), ('lp__isnull', False)), models.Q(models.Q(('role', 'LP'), _negated=True), ('lp__isnull', True)), _connector='OR'), name='membership_lp_iff_lp_role')],
            },
        ),
    ]
